### ISSUE TITLE
All counters returning ERROR [0002] PAGE INVALID

### ISSUE THREAD

**Issue by andresbezem** [damiankw/LikeMonitor#1]
Hi, I've tried it, even leaving your accounts in config.php but it gives me a ERROR [0002] PAGE INVALID in the 3 counters. Any idea why?

**Comment by damiankw** [comment]
The only thing I can think of is that you don't have curl installed on the system/php.

You can do a quick test by going to the following page under the instance: /get_twitter.php?page=gameroom_au

Let me know the output of that, it's meant to only show you the counter data, but if you're missing components it should bring up some PHP errors, or other. Let me know what it does.

**Comment by andresbezem** [comment]
You were right. It's installed now. The counter of instagram works, but for some reason I still get the same error for facebook. (chipichipibombon is the page of FB)

**Comment by damiankw** [comment]
Weird. Facebook works for me, and it uses exactly the same method of pulling data as Instagram and Twitter use. For me it brings up 1,831.

Does the issue happen when you leave the default config.php in place?

Try going to /get_facebook.php?page=chipichipibombon and let me know if there's any error messages. Also try chucking the code at the bottom of this post into a new file and see what it does, give me any output.

Also, nom nom ice cream.

```
<?php
  // build the URL for Facebook
  $URL = 'https://www.facebook.com/plugins/fan.php?connections=100&id=chipichipibombon';

  // set up CURL and execute (we are making out to be a browser here)
  $CURL = curl_init($URL);
  curl_setopt($CURL, CURLOPT_POST, false );
  curl_setopt($CURL, CURLOPT_FOLLOWLOCATION, true );
  curl_setopt($CURL, CURLOPT_USERAGENT, "Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.7.12) Gecko/20050915 Firefox/1.0.7");
  curl_setopt($CURL, CURLOPT_HEADER, false );
  curl_setopt($CURL, CURLOPT_RETURNTRANSFER, true );
  $HTML = curl_exec($CURL);

  // print out html for testing
  echo $HTML;
  echo '<hr>';

  // check if there is a valid return, if not the page must be invalid (this will be outdated after 1bil followers on a page. i'm not good at regex)
  if (!preg_match('/>(\d{1,3}\,\d{1,3}\,\d{1,3}\,\d{1,3}|\d{1,3}\,\d{1,3}\,\d{1,3}|\d{1,3}\,\d{1,3}|\d{1,3}) likes</', $HTML, $MATCH)) {
    echo 'ERROR [0002] PAGE INVALID';
  }

  // return the solid number with no commas
  $TOTAL = sprintf('%06d', str_replace(',', '', $MATCH[1]));

  // output whatever is required
  echo $TOTAL;
?>
```

**Comment by andresbezem** [comment]
/get_facebook.php?page=chipichipibombon gives me an ERROR [0002] PAGE INVALID

here’s an screenshot of what happen when I go to a page with the code you just sent me:



Also, my ice cream is amazing… if you are ever in Berlin….

**Comment by andresbezem** [comment]
/get_facebook.php?page=chipichipibombon gives me an ERROR [0002] PAGE INVALID

when I go to a page with the code you just sent me I see a bit of my fb page with the amount of followers

Also, my ice cream is amazing… if you are ever in Berlin….

**Comment by andresbezem** [comment]
sorry, underneath the print from facebook, there is a ERROR [0002] PAGE INVALID

**Comment by andresbezem** [comment]
![screen shot 2018-10-21 at 15 29 42](https://user-images.githubusercontent.com/44338510/47268463-c771ee80-d551-11e8-9aac-cf34ce2554c6.png)

**Comment by andresbezem** [comment]
I just reinstalled all the files AS you have them here, with your ids. Instagram and twitter work fine. FB still gives the same error 2

**Comment by damiankw** [comment]
I can't see a reason why it wouldn't work, but if you let me know your php version and operating system, I'll do some testing and see if I can't replicate it!

**Comment by andresbezem** [comment]
The server is running php 5.6 on Linux

**Comment by damiankw** [comment]
Which distribution/version of Linux is it? It shouldn't matter, but you never know.

**Comment by andresbezem** [comment]
I honestly have no clue. I just saw on my server that is linux, but no idea which distribution

**Comment by andresbezem** [comment]
Any luck? :)

**Comment by damiankw** [comment]
Hey man, I haven't had a chance to check it out unfortunately, a bit busy with work. I would hazard a guess that it's something to do with the way preg_match() works in PHP5 though, given it's a four year old version of PHP it might have changed quite a bit!

It's just strange, because the twitter and instagram portions all use the same technique to pull data.

Is there any chance you'd be able to upgrade PHP on your system to at least 7 and see how it works? I know this can be a huge task, especially if you have a heap of other systems running that require older functions.

Alternatively, given that it is essentially just a counter, the entire repository is compatible with Heroku, you could fork it, modify the config.php, then host with the free tier Heroku, that's what I do for my brothers place - https://gameroomau.herokuapp.com/ - I have noticed that if it's on 24/7 with a 5sec delay on updates it will usually use up your free tier usage in about 20 days, so it might pay to change it to at least a minute.
